runtime: nodejs14 
handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/app/\1
    upload: dist/app/(.*)(|\.map)
  - url: /.*
    static_files: dist/app/index.html
    upload: dist/app/.*